# Generated by Django 4.0.5 on 2022-06-25 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 8, 34, 52, 718691, tzinfo=utc)),
        ),
    ]
